all: clean compile run


compile: hw6.c
	@echo "----------------Compiling-----------------"
	@gcc -o hw6 hw6.c -lm -lrt

run:
	@echo "----------------Running----------------"
	@./hw6

clean:
	@echo "BERKAY EMRE KESKIN - HW6 - 210104004032"
	@echo "----------------Cleaning----------------"
	@rm -f *.o
	@rm -f hw6
